server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myspringboot?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=UTC
    username: admin
    password: admin
  application:
    name: my_springboot
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.beeb.myspringboot.model
  configuration:
    map-underscore-to-camel-case: true
nacos:
  config:
    server-addr: 127.0.0.1:8848
    namespace: 15aff825-0afd-4c27-becf-1c008bdadd08
  discovery:
    server-addr: ${nacos.config.server-addr}
